### ISSUE TITLE
[Suggestion] Support for other keyboards

### ISSUE THREAD

**Issue by qVoidreaver** [SpaceCat97/SpaceCats-Wikis#12]
I'm requesting support for a few keyboards that differ little from English (some are pretty much just accents on letters and a letter like "ç").
 Of course, I'm only requesting a few keyboards because I think it would be less work to go slowly, but in the future it's obvious that support for all keyboards would be ideal. 

 Anyway, thanks for your attention and have a nice day!

**Comment by SpaceCat97** [comment]
Added in version 20.11.0
