### ISSUE TITLE
CVT Workers conflict/incompatibility

### ISSUE THREAD

**Issue by AusPakeha** [SpaceCat97/SpaceCats-Wikis#14]
Minecraft version: 1.20.1

Mod version:20.22.0

Mod-Loader: (fabric/forge)
Forge

Description:
Conflict between CVT and Villager Workers mod known?
Not sure if it's an actual conflict, but it is overwriting some professions and i don't think CVT is picking up on that.

Response by Workers dev:

talhanation — Today at 4:28 PM
worker villagers are puppets they cant trade

Steps to reproduce:
Exporting professions with /exportCVT shows "profession": workers:----" instead of "profession": minecraft:----"

Log:
no log

**Comment by SpaceCat97** [comment]
The dev of "Villager Workers" states that villager workers are puppets and cant trade.
This issue is not caused by CVT.
