### ISSUE TITLE
All.json - Can't Get it to Work & Adding Wandering Traders from Other Mods

### ISSUE THREAD

**Issue by DumbXBoxAcct** [SpaceCat97/SpaceCats-Wikis#15]
Hi - 

Thanks for a couple of fabulous mods!  I use CVT & CVP together and they easily do what I've been struggling to do with a bunch of other mods for quite some time now.

I saw that you can use an "all.json" script to apply a trade across all professions.  I'm attaching the all.json file that I've been trying to use and I'm hoping that you can tell me how to correct it, since it doesn't seem to apply its trade to any profession.

Just for the record, I'm using CVT 20.23.0 for Fabric, MC 1.21.0 and Fabric Loader 0.15.3.  I have a massive number of other mods loaded, but since CVT works perfectly with them otherwise, I don't think that they're the problem.

Also, do you foresee adding support for wandering traders added by other mods?  Examples would be the "Wandering Winemaker" in Vinery and the "Red Merchant" in Supplementaries.  Haven't had any luck getting them working with CVT using the example "wanderer.json" script that you provide, customized with their namespaces and professions.

Thanks for your guidance, like I said, great mod(s)!

[all.json](https://github.com/SpaceCat97/SpaceCats-Wikis/files/14233698/all.json)

**Comment by SpaceCat97** [comment]
I'll give the all.json a test and reach out to you.

Regarding the compatibility for other wanderers, I'll have to do some testing. It currently only works with the vanilla wanderer. Please could you link one of the mods that add these traders you are on about?

Thank you for the kind words!

**Comment by DumbXBoxAcct** [comment]
Appreciate your quick response!  Here are links for the mods which I mentioned:

- Supplementaries:    https://www.curseforge.com/minecraft/mc-mods/supplementaries  (Red Merchant wanderer)
- Vinery:    https://www.curseforge.com/minecraft/mc-mods/vinery   (Wandering Winemaker wanderer)

**Comment by DumbXBoxAcct** [comment]
Actually, if you could just let me know what the value of "profession" should be in the all.json file, I suspect that might do it. I've tried "profession": "global", "profession": "all" and "profession": "" all without success.

**Comment by SpaceCat97** [comment]
Sorry for the delay in sorting this. I will be fixed in the next release.

**Comment by DumbXBoxAcct** [comment]
Super, thank you for keeping it in mind, I appreciate it!On May 29, 2024, at 4:28 AM, SpaceCat97 ***@***.***> wrote:﻿
Sorry for the delay in sorting this. I will be fixed in the next release.
