### ISSUE TITLE
[Idea] [ASB] Dimension Conditions and Tag Support

### ISSUE THREAD

**Issue by Z3R0Presence** [SpaceCat97/SpaceCats-Wikis#17]
Just a suggestion to add support for conditions based on dimensions, similar to biomes, the support of tags within conditions / ItemKeys and a flying condition / InAir condition.

eg. 
"conditions": [
                {
                    "type": "inBiome",
                    "extra": "#minecraft:is_jungle"
                }
            ]

"conditions": [
                {
                    "type": "inDimension",
                    "extra": "minecraft:the_nether"
                }
            ]

"conditions": [
                {
                    "type": "inAir"
                }
            ]

"conditions": [
                {
                    "type": "isFlying"
                }
            ]

If any of these are possible already (outside of just adding tons of bonuses), just tell me how lol

**Comment by Z3R0Presence** [comment]
In addition to this, maybe even detriments if the condition is not met (although this could technically already be performed by just making conditions with negative effects)

**Comment by SpaceCat97** [comment]
Accepted features:
- In dimension condition
- Inverted conditions (eg. not in dimension)

Refused features:
- Biome tags
- In air/flying

The accepted features will be available in version 13.
