### ISSUE TITLE
Defining "amountRange" returns unintended result. 

### ISSUE THREAD

**Issue by Grise0** [SpaceCat97/SpaceCats-Wikis#18]
Using trade example below:
	        {
         "isRare":false,
         "offer":{
            "itemKey":"croptopia:cranberry_seed",
            "amount":6
         },
         "request":{
            "itemKey":"coinsje:copper_coin",
            "amount":31,
			"amountRange":40
         },
         "tradeExp":4,
         "maxUses":5,
         "priceMultiplier":0.0,
         "demand":0,
         "tradeLevel":1
      },
      
   Returns trades above 40, rather than in range of 31 and 40.
   
   Changing amountRange to 9 returns the intended result.

**Comment by SpaceCat97** [comment]
This will be fixed in the next update
