### ISSUE TITLE
ASB curio integration/ 1.20.1 spacecatasb 20.12.0

### ISSUE THREAD

**Issue by whipeoff** [SpaceCat97/SpaceCats-Wikis#19]
{
  "armorSetName": "Exoskeleton",
  "performanceMode": true,
  "head": {
    "itemKey": "dreadsteel:dreadsteel_helmet",
    "mustBeEmpty": false
  },
  "chest": {
    "itemKey": "dreadsteel:dreadsteel_chestplate",
    "mustBeEmpty": false
  },
  "legs": {
    "itemKey": "dreadsteel:dreadsteel_leggings",
    "mustBeEmpty": false
  },
  "boots": {
    "itemKey": "dreadsteel:dreadsteel_boots",
    "mustBeEmpty": false
  },
  "curios":[
    {
        "itemKey":"aether:golden_pendant"
    }
  ],
  "fullSetBonuses": [
    {
      "type": "attribute",
      "name": "attributeslib:elytra_flight",
      "value": 1.0,
      "modifierUUID": "2d623297-7497-477b-a5c9-d12ee23327da",
      "description": "built-in wings",
      "attributeOperation": 0,
      "interactionType": "self",
      "interactionDuration": 300,
      "hideBonusDescription": true,
      "onlyImmuneToNewEffects": false
    },
    {
      "type": "attribute",
      "name": "forge:step_height_addition",
      "value": 1.0,
      "modifierUUID": "ccf77827-ccaa-400d-8c33-61d8bf756af7",
      "description": "step assist",
      "attributeOperation": 0,
      "interactionType": "self",
      "interactionDuration": 300,
      "hideBonusDescription": false,
      "onlyImmuneToNewEffects": false
    },
    {
      "type": "attribute",
      "name": "minecraft:generic.movement_speed",
      "value": 0.17,
      "modifierUUID": "93aee6ee-b675-4225-bedf-0df3d251c181",
      "description": "speed boost",
      "attributeOperation": 0,
      "interactionType": "self",
      "interactionDuration": 300,
      "hideBonusDescription": false,
      "onlyImmuneToNewEffects": false
    },
    {
      "type": "attribute",
      "name": "puffish_skills:player.jump",
      "value": 0.2,
      "modifierUUID": "eab23b49-9b0d-49f9-99f1-34b01376ac3c",
      "description": "jump boost",
      "attributeOperation": 0,
      "interactionType": "self",
      "interactionDuration": 300,
      "hideBonusDescription": false,
      "onlyImmuneToNewEffects": false
    },
    {
      "type": "effect",
      "name": "minecraft:night_vision",
      "value": 0.0,
      "interactionType": "self",
      "interactionDuration": 300,
      "description": "night vision",
      "hideBonusDescription": false,
      "onlyImmuneToNewEffects": false
    },
    {
      "type": "effect",
      "name": "parcool:inexhaustible",
      "value": 0.0,
      "interactionType": "self",
      "interactionDuration": 300,
      "description": "inexhaustible",
      "hideBonusDescription": false,
      "onlyImmuneToNewEffects": false
    },
    {
      "type": "effect",
      "name": "occultism:double_jump",
      "value": 1.0,
      "interactionType": "self",
      "interactionDuration": 300,
      "description": "air jump",
      "hideBonusDescription": false,
      "onlyImmuneToNewEffects": false
    }
  ],
  "hideGeneratedTooltip": false
}

Working everything except curio integration for some reason. Any trying to use curio integration sucks

**Comment by whipeoff** [comment]
"head": {
    "itemKey": "minecraft:golden_helmet",
    "mustBeEmpty": true
  },
  "chest": {
    "itemKey": "minecraft:golden_chestplate",
    "mustBeEmpty": true
  },
  "legs": {
    "itemKey": "minecraft:golden_leggings",
    "mustBeEmpty": false
  },
  "boots": {
    "itemKey": "minecraft:golden_boots",
    "mustBeEmpty": true
  },
  
  same thing here. If i turnoff mustbeempty - all works. If set has "mustBeEmpty": true - set just stops doing anything

**Comment by SpaceCat97** [comment]
Please make sure you are using the correct configuration. You must use "additionalSetPieces" instead of "curios" - [WIKI HERE](https://github.com/SpaceCat97/SpaceCats-Wikis/wiki/Armor-Set-Bonuses)

As for your issue with the mustBeEmpty field, I have tested this in my development environment and had no issues. Please could you download the latest version (Version 13, releasing tonight) and test again.
