### ISSUE TITLE
ASB suggestion: Fully hide description if left empty

### ISSUE THREAD

**Issue by Sereliana** [SpaceCat97/SpaceCats-Wikis#20]
When trying to create a set that gives multiple attributes, but only has one description that sums up all the effects, there is no way to properly hide unnecessary descriptions. An empty description always displays "self", which clutters the UI. 

![Screenshot_39](https://github.com/SpaceCat97/SpaceCats-Wikis/assets/72799237/1712c132-bee7-42d0-ada3-3435943c57c9)

Adding a way to hide these empty descriptions would be nice.

**Comment by SpaceCat97** [comment]
This will be added in version 13.
