### ISSUE TITLE
CVT suggestion: Config file to set which operator level can use the commands.

### ISSUE THREAD

**Issue by Turcul** [SpaceCat97/SpaceCats-Wikis#21]
You should add a config file so we could set which operator level can use the commands from the mod. I have a few level 2 ops on my server and i trust them but it would be very useful.

**Comment by SpaceCat97** [comment]
The mod commands are already configured for op level 2, have you tested this with your ops to see if they have access?

**Comment by Turcul** [comment]
They do have acces. The idea is that i would love to be able to configure the commands for op level 4 so only i (the server administrator) can acces them.

**Comment by SpaceCat97** [comment]
This will be added in the next update
