### ISSUE TITLE
Apparent syntax bug

### ISSUE THREAD

**Issue by TynotWolfDragon** [SpaceCat97/SpaceCats-Wikis#22]
Making a custom trade, using the templates spacecat uploaded on their discord, and ran into a problem with part i didn't edit.

![image](https://github.com/SpaceCat97/SpaceCats-Wikis/assets/16494408/5b3766fa-dba9-4fec-8832-cb26136ed71f)

7

![image](https://github.com/SpaceCat97/SpaceCats-Wikis/assets/16494408/72cf130c-f657-4789-8f9b-4e166ef66bef)

and 8

![image](https://github.com/SpaceCat97/SpaceCats-Wikis/assets/16494408/feb7c6a2-c024-4a8d-bc03-7257951f414c)

The version im using is 1.20.1 on forge.

**Comment by SpaceCat97** [comment]
Please try using "effectKey" instead of "potionKey"

**Comment by SpaceCat97** [comment]
No response, closing.
