### ISSUE TITLE
CVT: Unable to Set Certain Potion Effects in Trade Config File

### ISSUE THREAD

**Issue by warrentode** [SpaceCat97/SpaceCats-Wikis#23]
Version: Minecraft 1.19.2 in Forge (customvillagertrades-forge-19.24.0)

The following lines of code produce an uncraftable potion with an NBT for color that wasn't put in the config file:

`{
        "additionalRequest": {
        "itemKey": "minecraft:potion",
        "amount": 1,
        "priceModifier": 0,
        "advancedNBTData": "{Potion:\"minecraft:awkward\"}"
      }
}`

`{
        "additionalRequest": {
        "itemKey": "minecraft:potion",
        "amount": 1,
        "priceModifier": 0,
        "advancedNBTData": "{Potion:\"minecraft:thick\"}"
      }
}`

`{
        "additionalRequest": {
        "itemKey": "minecraft:potion",
        "amount": 1,
        "priceModifier": 0,
        "advancedNBTData": "{Potion:\"minecraft:water\"}"
      }
}`

And the following lines of code only produce the effect key is invalid error, thus failing to load the trade entirely:

`{
        "additionalRequest": {
        "itemKey": "minecraft:potion",
        "amount": 1,
        "priceModifier": 0,
        "effects": [
          {
            "effectKey": "minecraft:awkward",
            "duration": 1200,
            "level": 0,
            "isVisible": true,
            "potionKey": "minecraft:awkward"
          }
        ]
      }
}`

`{
        "additionalRequest": {
        "itemKey": "minecraft:potion",
        "amount": 1,
        "priceModifier": 0,
        "effects": [
          {
            "effectKey": "minecraft:thick",
            "duration": 1200,
            "level": 0,
            "isVisible": true,
            "potionKey": "minecraft:thick"
          }
        ]
      }
}`

`{
        "additionalRequest": {
        "itemKey": "minecraft:potion",
        "amount": 1,
        "priceModifier": 0,
        "effects": [
          {
            "effectKey": "minecraft:water",
            "duration": 1200,
            "level": 0,
            "isVisible": true,
            "potionKey": "minecraft:water"
          }
        ]
      }
}`

**Comment by SpaceCat97** [comment]
**This will be fixed in the next update.**

A few notes:
- Your potion will have the purple colour, but if correctly configured the name will show correctly
- To change the colour, you can use the customColorR, G and B values seen here: https://github.com/SpaceCat97/SpaceCats-Wikis/wiki/Trade-Item-Object

The best way to do this would be to use the advancedNBTData as you've done in your example, and do not define any effects.

**Comment by warrentode** [comment]
> The best way to do this would be to use the advancedNBTData as you've done in your example, and do not define any effects.

Will doing it this way get me the water?

**Comment by soupstore101** [comment]
im having issues with weakness potions working. im trying to make a trade for weakness potions but it gives the effect but the name and color are that of uncraftable potions. also the traded potion has 2 nbt tags which im not sure how to view to see what they are. any help is appreciated
