### ISSUE TITLE
ASB suggestion: add translation text of entity attribute

### ISSUE THREAD

**Issue by Karashok-Leo** [SpaceCat97/SpaceCats-Wikis#24]
Each registered attribute has its own translation key. Maybe their texts can be displayed as translation texts in tooltip.

**Comment by SpaceCat97** [comment]
Try using the "description" field here: https://github.com/SpaceCat97/SpaceCats-Wikis/wiki/Bonus-Object

If you do something like "tooltip.bonus.MY_BONUS_TEXT" then you can set it in the language file like this:
"tooltip.bonus.MY_BONUS_TEXT": "my bonus text"

**Comment by Karashok-Leo** [comment]
This will be a huge workload. as I have hundreds of bonuses. 😭

**Comment by Karashok-Leo** [comment]
This will be a huge workload. as I have hundreds of bonuses. 😭

**Comment by SpaceCat97** [comment]
That's the way it has to be unfortunately. I reviewed this properly and tried adding something in but the solution already exists. Even if I added a new solution in you would still have to add a bunch of entries into your translation file.
