### ISSUE TITLE
(DOT COIN MOD) Trinket Support?

### ISSUE THREAD

**Issue by Dumpling00** [SpaceCat97/SpaceCats-Wikis#29]
Hello! This is a bit of a situational request. I'm on Fabric 1.20.1, would it be possible to make the wallet compatible with Switchy or be an actual bag compatible with one of the trinkets slot? Maybe the leggings one so that it wouldn't conflict with any equipped backpack.

The reason I ask this is because I'm running a bit of an adventure game with Switchy, where each player can have different character presets, and through some of its modules, it's possible to make things like health, inventory, exp, trinkets etc. unique to each character preset.
Right now, because the wallet is its own thing, each preset shares the same wallet. I'd like to make it so each character can have their own wallet and money.

Thank you for your consideration!

**Comment by SpaceCat97** [comment]
You can use trinkets independently to add your own slots (datapacks/config). All you will then have to do is disable the wallet in the config. I will not be implementing the mod with trinkets in this way.
