### ISSUE TITLE
"amount"  when exported does not match 

### ISSUE THREAD

**Issue by BlackAures1** [SpaceCat97/SpaceCats-Wikis#3]
![image](https://github.com/SpaceCat97/SpaceCats-Wikis/assets/43911230/39c5f260-152f-485d-8fd7-f0dcbdd1a21d)

`/ exportCVT`  does not export the real price, but sets the value to 1 for all trades.
customvillagertrades-forge-19.20.0

**expected behavior:** exports will export real price

**Comment by SpaceCat97** [comment]
Thank you for reporting, I will investigate and report my findings

**Comment by SpaceCat97** [comment]
Confirmed bug, solution will be in version 21.
