### ISSUE TITLE
[ARMOR SET BONUSES] [BUG] "InteractionType" String or Bolean "performanceMode".

### ISSUE THREAD

**Issue by qVoidreaver** [SpaceCat97/SpaceCats-Wikis#33]
{
  "armorSetName": "Wither Debuff",
  "performanceMode": false,
  "mainHand": {
    "itemKey": "minecraft:iron_sword",
	"mixAndMatch": [
	 "minecraft:diamond_sword"
	]
  },
  "fullSetBonuses": [
	{
      "type": "effect",
      "name": "minecraft:wither",
      "value": 0,
      "interactionType": "attack",
      "interactionDuration": 140
    }
  ],
  "hideGeneratedTooltip": true,
  "customTooltips": [
	"Your attacks apply anti-healing for 7s"
  ]
}

 (NOT TESTED IN OTHER VERSIONS ONLY 1.18.2, but I believe this is happening in all of them)

This is the file I created and, apparently, the string "InteractionType", when used as "attack", doesn't work even when "performanceMode"= false. 
 I believe that the problem may be the "InteractionType" string that is not being applied correctly to the entities. 

note: the "InteractionType" string when in "attack" works normally in the player.

**Comment by SpaceCat97** [comment]
I've tested this exact config in the latest 1.18.2 and 1.20.1 version - no issue. Closing
