### ISSUE TITLE
/exportCVT doesn't export wandering trader trades

### ISSUE THREAD

**Issue by Garonne** [SpaceCat97/SpaceCats-Wikis#36]
I wanted to change all trades from emeralds to dot-coin-currencies.
So I exported all trades with /exportCVT.
This worked even for modded villagers. Just the wandering trader wasn't exported.

**Comment by SpaceCat97** [comment]
/exportCVT currently only works with professions by design

**Comment by SpaceCat97** [comment]
This will be available in the next release
