### ISSUE TITLE
Iron's spellbooks mob trades not exported

### ISSUE THREAD

**Issue by efficient-efi** [SpaceCat97/SpaceCats-Wikis#37]
Iron's spellbooks mod has some tradeable mobs, but when I tried to export them with /exportCVT I got this error and could not do it.
![2024-05-11_23 35 38](https://github.com/SpaceCat97/SpaceCats-Wikis/assets/117365833/fef164bd-fafe-4cd1-b331-104cf63d21d1)

**Comment by SpaceCat97** [comment]
I have applied a fix that **might** fix this issue, it will be available in the next release.
