### ISSUE TITLE
[ASB] Suggestion: Condition For Y Level

### ISSUE THREAD

**Issue by Z3R0Presence** [SpaceCat97/SpaceCats-Wikis#38]
Just a suggestion: include a condition that tests a player's Y level against a value or range.

This test can determine whether a player's Y level is greater than, less than, or within a range (e.g., <= 50, >= 10). .
When defining a set, the player could define the operation (less than, greater than, within) and then the appropriate variables to define this (y1, y2, etc., only two at most). 

This could be a useful condition for some niche armour sets.

**Comment by SpaceCat97** [comment]
This will be added in the next release.
