### ISSUE TITLE
conditions (suggestion)

### ISSUE THREAD

**Issue by ReedJr** [SpaceCat97/SpaceCats-Wikis#4]
Is it ok that you make a conditions/type/string for biomes and potion effects? Maby a value like "inbiome", "oneffect", or "effectedby" might be useful.

**Comment by ReedJr** [comment]
here is also a link to what I am talking about.
https://github.com/SpaceCat97/SpaceCats-Wikis/wiki/Condition-Object

**Comment by SpaceCat97** [comment]
Condition for biome - accepted and will look into.

Condition for effects/potions - refused. Because the mod uses effects and potions already it could result in endless loops if incorrectly used.

**Comment by SpaceCat97** [comment]
Leaving this issue open until the feature is released.

**Comment by SpaceCat97** [comment]
Added in version 20.11.0
