### ISSUE TITLE
[ASB] (Suggestion) Add an optional "interval" timer to permanent potion set effects, as well as an optional "cooldown" to attack/interact effects

### ISSUE THREAD

**Issue by LynxGrimbane** [SpaceCat97/SpaceCats-Wikis#40]
1.) For my first suggestion, I think it'd greatly diversity the options/choices in armor for modpacks in ways such as:

- Having an armor apply a really strong effect but without 100% uptime.
- Having an armor with really strong attributes, but in turn debuffs you on certain intervals. 
An in turn, players can decide whether they'd choose between sets that have a consistent weak effect (or none at all), or armor that provides big but inconsistent boons. 

2.) For my second suggestion, I believe this option would allow for better balancing/fine tuning kits. 
- Having it on a timer means that similar to the above point, I can balance things accordingly. I wouldn't have to worry as much about giving a character an "effect" that is too strong- as I can compensate by adding a lengthy cooldown. 

The mod is still great as is but I do hope these features are possible to implement!

**Comment by SpaceCat97** [comment]
I will not be adding timers to effects. My reasoning is because the mod is already rather resource-demanding and adding in timers will make it even more so.
