### ISSUE TITLE
[ASB] Suggestion - Weapons/Tools stats.

### ISSUE THREAD

**Issue by ImAGh0st** [SpaceCat97/SpaceCats-Wikis#42]
Just a quick example of what I had in mind about it. TYSM for taking ur time to read and even consider this!

{
"swordBonuses":[  
"weaponName": "minecraft:diamond_sword",
 ]
},  
"whilemainHand":[
{
      "type": "attribute",
      "name": "minecraft:strength",
      "value": 1.0,
      "modifierUUID": "9b63caad-d42b-4db3-bc75-818fa9bf016d",
      "description": "Strength 1",
      "interactionType": "self",
      "interactionDuration": 300,
      "hideBonusDescription": false,
}
 ],

**Comment by SpaceCat97** [comment]
This is already achievable using the mod, take a look at the mainHand/offHand features.
