### ISSUE TITLE
[CVT] Over levelling enchantments

### ISSUE THREAD

**Issue by eduardofz12** [SpaceCat97/SpaceCats-Wikis#45]
Following up your message on discord,

Hi, I created a trade for an enchanted equipment with this setting
```
{
     "enchantmentKey": "random",
     "enchantmentLevel": -1,
     "maxEnchantmentLevel": 6
}
```
And it totally works the way it is designed, but the problem is that it makes any enchantment be able to get to level 6. I had an enchantment with max level being 1 (on apotheosis config) and it created the item with this enchantment at level 6. Is it possible to make random enchantments not be overleveled?

**Comment by SpaceCat97** [comment]
This ticket would be solved if I was to implement https://github.com/SpaceCat97/SpaceCats-Wikis/issues/44 (issue 44) - therefore I am closing this ticket.
