### ISSUE TITLE
"removeOtherTrades":true no work for wanderer trader

### ISSUE THREAD

**Issue by BlackAures1** [SpaceCat97/SpaceCats-Wikis#5]
![image](https://github.com/SpaceCat97/SpaceCats-Wikis/assets/43911230/164d5956-79cd-4e3e-a08b-08f46931b859)
![image](https://github.com/SpaceCat97/SpaceCats-Wikis/assets/43911230/90df0d6a-9a50-4503-b41d-06e4ca1b3cfe)

Quark, Upgrade Uquatic, Apotheosis and other mods ignores "removeOtherTrades":true for a wandering trader. For regular villagers, it works
1.19.2
[wanderer.json](https://github.com/SpaceCat97/SpaceCats-Wikis/files/13503711/wanderer.json)
[latest.log](https://github.com/SpaceCat97/SpaceCats-Wikis/files/13503716/latest.log)

**Comment by SpaceCat97** [comment]
does it remove the vanilla trades?

**Comment by SpaceCat97** [comment]
I'll do some testing

**Comment by BlackAures1** [comment]
No news yet? 👉👈

**Comment by SpaceCat97** [comment]
No, please understand that I do this in my spare time. This ticket will be updated when I have time to do so.

**Comment by BlackAures1** [comment]
I'm sorry if that sounded harsh, I didn't plan to rush you. Just thought you had failed to replicate the bug/no function.

**Comment by SpaceCat97** [comment]
I was able to recreate this issue in my dev environment. Will be fixed in the next release.

**Comment by SpaceCat97** [comment]
I've added some functionality that will get rid of some modded trades, however different mods add trades in different ways (for example, quark forces trades). For mods that still add trades you will have to find a config option to disable them.

**Comment by SpaceCat97** [comment]
Fixed in version 23 for all LTS versions
