### ISSUE TITLE
[ASB] - Suggestion: Multiple Partial Set Bonuses

### ISSUE THREAD

**Issue by QuillVest** [SpaceCat97/SpaceCats-Wikis#53]
Simple _possible_ future addition, having more than one partial set bonus, for example a (2), (3) + (4) set bonus on an armor set.

**Comment by SpaceCat97** [comment]
This has already been requested - closing this ticket as it is a duplicate.

https://github.com/SpaceCat97/SpaceCats-Wikis/issues/34
