### ISSUE TITLE
[ABS] add the feature for attributes modifiers to be applied to attacked mobs when using the "attack" interaction type

### ISSUE THREAD

**Issue by Indigomist** [SpaceCat97/SpaceCats-Wikis#56]
Example, I tried to make it to where whenever I attacked a mob while wearing a armor set with a given bonus that when I attack a mob it reduces that mobs max health to 80% of the current amount, using a value of -0.2 and operation 2

Another example would be when I attack a mob it lowers the mobs attack damage by a given value and operation 0

**Comment by SpaceCat97** [comment]
I will not be adding this as it would mean that the mod would have to track the attributes of each attacked mob for the entire configured length of the effect - this would be far too performance heavy.
