### ISSUE TITLE
hideBonusDescription inconsistency 

### ISSUE THREAD

**Issue by LaylaRosaleen** [SpaceCat97/SpaceCats-Wikis#58]
"hideBonusDescription" will not always work, inconsistently hiding bonuses on some armor sets but not on others. An example (found from the discord support thread) would be iron armor or battlemage (ars nouveau) armor hiding a description successfully, but terrasteel (botania) not hiding that same description.

Minecraft version: 1.20.1
ASB version: forge-20.13.1

**Comment by LaylaRosaleen** [comment]
after a bit more analysis of what is and is not working, I'm pretty sure it's an issue with partial set bonuses, as all of the problems with hideBonusDescription are contained within partial set bonuses

**Comment by SpaceCat97** [comment]
Bug found, will be fixed in the next release.
