### ISSUE TITLE
[CVT] supplementaries loading arror

### ISSUE THREAD

**Issue by 2929762171** [SpaceCat97/SpaceCats-Wikis#7]
supplementaries-1.16.5-0.18.7
It work correctly with customvillagertrades-1.16_V17, 
crash with customvillagertrades-forge-16.21.0 .
[crash-2023-12-15_05.31.09-fml.txt](https://github.com/SpaceCat97/SpaceCats-Wikis/files/13678711/crash-2023-12-15_05.31.09-fml.txt)

**Comment by SpaceCat97** [comment]
Supplementaries uses a feature from this mod that has been removed. I've notified the author but you may want to reach out to them directly.

**Comment by SpaceCat97** [comment]
@2929762171 I've spoken with the author, you are using an old and unsupported version of supplementaries.
You have 2 options:
1. If you want it fixed you will definitely have to reach out to the author and hope they update
2. Use CVT version 17
